package com.ritense.valtimoplugins.samenwerkfunctionaliteit.autoconfigure

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties
class SamenwerkfunctionaliteitConfiguration